import React, { useState } from 'react';
import Navbar from '../components/common/Navbar';
import Sidebar from '../components/common/Sidebar';
import { storageService } from '../services/storageService';

const NotificationsPage = () => {
  const [notifications, setNotifications] = useState(storageService.getNotifications());

  const handleMarkAllRead = () => {
    const updated = storageService.markAllNotificationsRead();
    setNotifications(updated);
  };

  return (
    <div className="app-layout">
      <Navbar />
      <div className="portal-container">
        <Sidebar />
        <main className="portal-content">
          <div className="breadcrumb-trail">Home / Notifications</div>
          <div className="page-header-row">
            <div>
              <h1 className="page-main-heading">Notifications</h1>
              <p className="page-sub-heading">
                Updates generated by clearance activities and account actions.
              </p>
            </div>
            <button
              onClick={handleMarkAllRead}
              className="btn btn-pill-outline"
              style={{ padding: '0.4rem 1.25rem' }}
            >
              Mark all as read
            </button>
          </div>

          <div style={{ marginTop: '1.25rem' }}>
            {notifications.map(notif => (
              <div key={notif.id} className="notification-card-item">
                <div className="notification-left">
                  <div className="notification-icon-box">
                    {notif.icon}
                  </div>
                  <div>
                    <div className="notification-title">{notif.title}</div>
                    <div className="notification-text">{notif.text}</div>
                  </div>
                </div>
                <div className="notification-timestamp">
                  {notif.timestamp}
                </div>
              </div>
            ))}
          </div>
        </main>
      </div>
    </div>
  );
};

export default NotificationsPage;
